# Generated by Django 3.2.4 on 2021-06-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=32)),
                ('esal', models.FloatField()),
                ('eexp', models.FloatField()),
            ],
        ),
    ]
